baseURL = "http://example.org/"
languageCode = "zh-CN"
title = "八荒山人导航"
theme = "webstack-2"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = "八荒山人"
[params]
  author = "八荒山人"
  description = "使用Webstack Hugo的导航站"
[params.search]
  enable = true
[params.darkmode]
  enable = false